# --- Hugo .Site.Params for staging are all in this yaml ----------------------

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo: https://github.com/mrmxf/bruce-www-metarex-media
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo: https://github.com/metarex-media
