#                              _
#   ___  __ _   _ __    _ __  | |  ___
#  (_-< / _` | | '  \  | '_ \ | | / -_)
#  /__/ \__,_| |_|_|_| | .__/ |_| \___|
#                      |_|

# REMEMBER it's .gitpod.yml - use this file in a comparator

tasks:
  - init: |
      curl https://mrmxf.com/get/clog | bash
      sudo add-apt-repository ppa:rmescandon/yq
      sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      sudo chmod +x /usr/bin/yq


# port for server & godoc
ports:
  #hugo
  - port: 1313
    onOpen: open-browser
